openapi: 3.0.0
info:
  description: API del challenge de Damian
  version: "1.0.0-oas3"
  title: ChallengeDamian API
  contact:
    email: damian@avalith.net
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

paths:
  /auth/login:
    $ref: './paths/login.yaml'
  /auth/logout:
    $ref: './paths/logout.yaml'
  /event/{id}:
    $ref: './paths/eventGet.yaml'
  /events:
    $ref: './paths/eventAll.yaml'
  /notification:
    $ref: './paths/notificationUpdate.yaml'
  /notifications:
    $ref: './paths/notificationAll.yaml'
  /payment/{id}:
    $ref: './paths/paymentGet.yaml'
  /payments:
    $ref: './paths/paymentAll.yaml'
  /theatre/all:
    $ref: './paths/theatreAll.yaml'
  /theatre/profile:
    $ref: './paths/theatreProfile.yaml'
  /theatre/update:
    $ref: './paths/theatreUpdate.yaml'
  /theatre/{id}:
    $ref: './paths/theatreGet.yaml'
  /theatre-room/{id}:
    $ref: './paths/theatreGetRoom.yaml'
  /user/change-pass:
    $ref: './paths/userChangePassword.yaml'
  /user/forgot-password:
    $ref: './paths/userForgotPassword.yaml'
  /user/reset-password:
    $ref: './paths/userResetPassword.yaml'
  /user/theatre:
    $ref: './paths/userRegisterTheatre.yaml'
  /user/update-account:
    $ref: './paths/userUpdateAccount.yaml'
servers:
  - url: 'https://localhost:3000/api-docs/documentation'